/**
 * Google Drive PWA File Manager
 * Program: GoogleDrivePWA
 * Version: V0.6
 * Date: 2026-06-02
 *
 * Version log:
 * V0.6 - 2026-06-02
 * - 移除前端對刪除 / 改名操作的上傳者限制，改由 Google Drive 權限決定。
 * - 新增檔案列表 checkbox、全選 checkbox、已選取數量顯示。
 * - 新增批次刪除功能，採逐一刪除，單筆失敗不中斷其他刪除。
 * - 新增批次刪除進度與結果摘要。
 * - 新增 PWA icon 檔案，manifest.json 改用正式 icons 路徑。
 * - 手機版檔案列表改為卡片式 UI，按鈕與 Settings 版面優化。
 *
 * V0.5 - 2026-06-02
 * - 新增多檔案選擇與逐一上傳功能。
 * - 新增記住登入狀態與自動嘗試重新登入功能。
 *
 * V0.4 - 2026-06-02
 * - 程式 APP_VERSION 改為與 ZIP 檔版本一致。
 */
const CONFIG = window.APP_CONFIG;
const STORAGE_KEYS = {
  FOLDER_ID: "drive_pwa_folder_id",
  GOOGLE_CLIENT_ID: "drive_pwa_google_client_id",
  VERSION_CHECK_URL: "drive_pwa_version_check_url",
  REMEMBER_LOGIN: "drive_pwa_remember_login",
  LAST_LOGIN_EMAIL: "drive_pwa_last_login_email",
  LAST_LOGIN_TIME: "drive_pwa_last_login_time"
};
let tokenClient = null, accessToken = null, currentUserEmail = "", initializedClientId = "", autoSignInTried = false;
let currentFiles = [];
let selectedFiles = new Map();
const $ = (id) => document.getElementById(id);

const loginBtn=$("loginBtn"), logoutBtn=$("logoutBtn"), loginStatus=$("loginStatus"), clientIdStatus=$("clientIdStatus"), folderStatus=$("folderStatus");
const fileInput=$("fileInput"), uploadBtn=$("uploadBtn"), refreshBtn=$("refreshBtn"), fileTableBody=$("fileTableBody"), mobileFileList=$("mobileFileList"), messageBox=$("messageBox");
const operationInfo=$("operationInfo"), selectedFileInfo=$("selectedFileInfo"), operationProgressText=$("operationProgressText"), operationProgressBar=$("operationProgressBar");
const selectAllFilesCheckbox=$("selectAllFilesCheckbox"), batchActionBar=$("batchActionBar"), selectedCountText=$("selectedCountText"), batchDeleteBtn=$("batchDeleteBtn"), clearSelectionBtn=$("clearSelectionBtn");
const clientIdInput=$("clientIdInput"), folderIdInput=$("folderIdInput"), versionUrlInput=$("versionUrlInput"), rememberLoginInput=$("rememberLoginInput"), lastLoginInfo=$("lastLoginInfo");
const saveSettingsBtn=$("saveSettingsBtn"), clearSettingsBtn=$("clearSettingsBtn"), currentVersion=$("currentVersion"), cacheVersion=$("cacheVersion"), githubLatestVersion=$("githubLatestVersion"), checkUpdateBtn=$("checkUpdateBtn"), updateResult=$("updateResult");

document.addEventListener("DOMContentLoaded", initApp);
function initApp(){
  initTabs(); initSettings(); registerServiceWorker();
  loginBtn.addEventListener("click", signIn); logoutBtn.addEventListener("click", signOut);
  uploadBtn.addEventListener("click", uploadSelectedFiles); refreshBtn.addEventListener("click", listFiles); fileInput.addEventListener("change", updateSelectedFileInfo);
  selectAllFilesCheckbox.addEventListener("change", e=>toggleSelectAllFiles(e.target.checked));
  batchDeleteBtn.addEventListener("click", batchDeleteSelectedFiles); clearSelectionBtn.addEventListener("click", clearSelectedFiles);
  saveSettingsBtn.addEventListener("click", saveSettings); clearSettingsBtn.addEventListener("click", clearLocalSettings); checkUpdateBtn.addEventListener("click", checkForUpdates);
  updateClientIdStatus(); updateFolderStatus(); waitForGoogleIdentity();
}
function waitForGoogleIdentity(retry=0){if(window.google&&window.google.accounts){initGoogleIdentityIfPossible();return;} if(retry>30){showMessage("Google Identity Services 載入逾時，請確認網路連線後重新整理。","error");return;} setTimeout(()=>waitForGoogleIdentity(retry+1),200);}
function initGoogleIdentityIfPossible(){const clientId=getGoogleClientId(); if(!clientId){loginBtn.disabled=true;showMessage("請先到 Settings 設定 Google OAuth Client ID，儲存後再登入。","info");return;} if(!isValidClientIdFormat(clientId)){loginBtn.disabled=true;showMessage("OAuth Client ID 格式不正確，請到 Settings 修正。","error");return;} initializedClientId=clientId; tokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:CONFIG.SCOPES,callback:handleTokenResponse,error_callback:handleTokenError}); loginBtn.disabled=false; if(getRememberLogin()&&!autoSignInTried) autoSignIn();}
async function handleTokenResponse(tokenResponse){if(tokenResponse.error){showMessage(`登入失敗：${tokenResponse.error}`,"error");return;} accessToken=tokenResponse.access_token; await loadUserProfile(); loginBtn.classList.add("hidden"); logoutBtn.classList.remove("hidden"); loginStatus.textContent=currentUserEmail?`已登入：${currentUserEmail}`:"已登入 Google"; if(getRememberLogin()) saveLoginState(currentUserEmail); showMessage("登入成功。","success"); listFiles();}
function handleTokenError(error){if(error.type==="popup_failed_to_open")showMessage("登入視窗無法開啟，請允許瀏覽器彈出視窗。","error"); else if(error.type==="popup_closed")showMessage("登入視窗已關閉，尚未完成授權。","info"); else showMessage(`登入發生錯誤：${JSON.stringify(error)}`,"error");}
function signIn(){const clientId=getGoogleClientId(); if(!clientId){showMessage("請先到 Settings 設定 Google OAuth Client ID。","error");switchToSettingsTab();return;} if(!tokenClient||initializedClientId!==clientId) initGoogleIdentityIfPossible(); if(!tokenClient){showMessage("Google OAuth 尚未初始化。","error");return;} tokenClient.requestAccessToken({prompt:"consent"});}
function autoSignIn(){if(!tokenClient||autoSignInTried)return; autoSignInTried=true; const lastEmail=localStorage.getItem(STORAGE_KEYS.LAST_LOGIN_EMAIL)||""; loginStatus.textContent=lastEmail?`正在嘗試自動登入：${lastEmail}`:"正在嘗試自動登入..."; try{tokenClient.requestAccessToken({prompt:""});}catch{loginStatus.textContent="自動登入失敗，請手動登入";}}
function signOut(){if(accessToken&&window.google) google.accounts.oauth2.revoke(accessToken); accessToken=null; currentUserEmail=""; clearLoginState(); loginBtn.classList.remove("hidden"); logoutBtn.classList.add("hidden"); loginStatus.textContent="尚未登入"; fileTableBody.innerHTML=`<tr><td colspan="7" class="empty">請先登入</td></tr>`; mobileFileList.innerHTML=""; showMessage("已登出，已清除登入記憶。","success");}
async function loadUserProfile(){try{const res=await fetch("https://www.googleapis.com/oauth2/v3/userinfo",{headers:{Authorization:`Bearer ${accessToken}`}}); if(!res.ok)return; const data=await res.json(); currentUserEmail=data.email||"";}catch{currentUserEmail="";}}
function getGoogleClientId(){return localStorage.getItem(STORAGE_KEYS.GOOGLE_CLIENT_ID)||"";} function getFolderId(){return localStorage.getItem(STORAGE_KEYS.FOLDER_ID)||"";} function getVersionCheckUrl(){return localStorage.getItem(STORAGE_KEYS.VERSION_CHECK_URL)||CONFIG.DEFAULT_VERSION_CHECK_URL||"./version.json";} function getRememberLogin(){return localStorage.getItem(STORAGE_KEYS.REMEMBER_LOGIN)==="true";}
function saveLoginState(email){localStorage.setItem(STORAGE_KEYS.REMEMBER_LOGIN,"true"); if(email)localStorage.setItem(STORAGE_KEYS.LAST_LOGIN_EMAIL,email); localStorage.setItem(STORAGE_KEYS.LAST_LOGIN_TIME,new Date().toISOString()); updateLastLoginInfo();}
function clearLoginState(){localStorage.removeItem(STORAGE_KEYS.REMEMBER_LOGIN); localStorage.removeItem(STORAGE_KEYS.LAST_LOGIN_EMAIL); localStorage.removeItem(STORAGE_KEYS.LAST_LOGIN_TIME); if(rememberLoginInput)rememberLoginInput.checked=false; updateLastLoginInfo();}
function updateLastLoginInfo(){const email=localStorage.getItem(STORAGE_KEYS.LAST_LOGIN_EMAIL), time=localStorage.getItem(STORAGE_KEYS.LAST_LOGIN_TIME); lastLoginInfo.textContent=email?`上次登入：${email}，時間：${formatDate(time)}`:"尚未記錄登入狀態";}
function saveSettings(){const clientId=clientIdInput.value.trim(), folderId=folderIdInput.value.trim(), versionUrl=versionUrlInput.value.trim()||CONFIG.DEFAULT_VERSION_CHECK_URL; if(!clientId)return showMessage("請輸入 Google OAuth Client ID。","error"); if(!isValidClientIdFormat(clientId))return showMessage("Google OAuth Client ID 格式不正確。","error"); if(!folderId)return showMessage("請輸入 Google Drive 資料夾 ID。","error"); const previousClientId=getGoogleClientId(); localStorage.setItem(STORAGE_KEYS.GOOGLE_CLIENT_ID,clientId); localStorage.setItem(STORAGE_KEYS.FOLDER_ID,folderId); localStorage.setItem(STORAGE_KEYS.VERSION_CHECK_URL,versionUrl); localStorage.setItem(STORAGE_KEYS.REMEMBER_LOGIN,rememberLoginInput.checked?"true":"false"); updateClientIdStatus(); updateFolderStatus(); updateLastLoginInfo(); if(previousClientId!==clientId){tokenClient=null; accessToken=null; initializedClientId=""; autoSignInTried=false; loginBtn.classList.remove("hidden"); logoutBtn.classList.add("hidden"); loginStatus.textContent="尚未登入"; initGoogleIdentityIfPossible(); showMessage("設定已儲存於本機。OAuth Client ID 已更新，請重新登入。","success"); return;} showMessage("設定已儲存於本機。","success"); if(accessToken)listFiles();}
function clearLocalSettings(){if(!confirm("確定要清除本機設定與登入記憶嗎？"))return; Object.values(STORAGE_KEYS).forEach(k=>localStorage.removeItem(k)); clientIdInput.value=""; folderIdInput.value=""; versionUrlInput.value=CONFIG.DEFAULT_VERSION_CHECK_URL; rememberLoginInput.checked=false; githubLatestVersion.value="尚未檢查"; tokenClient=null; accessToken=null; initializedClientId=""; autoSignInTried=false; loginBtn.disabled=true; loginBtn.classList.remove("hidden"); logoutBtn.classList.add("hidden"); loginStatus.textContent="尚未登入"; updateClientIdStatus(); updateFolderStatus(); updateLastLoginInfo(); showMessage("本機設定已清除。","success");}
function initSettings(){currentVersion.value=CONFIG.APP_VERSION; cacheVersion.value=CONFIG.CACHE_NAME; githubLatestVersion.value="尚未檢查"; clientIdInput.value=getGoogleClientId(); folderIdInput.value=getFolderId(); versionUrlInput.value=getVersionCheckUrl(); rememberLoginInput.checked=getRememberLogin(); updateLastLoginInfo();}
function updateClientIdStatus(){const clientId=getGoogleClientId(); clientIdStatus.textContent=clientId?`OAuth Client ID：${maskClientId(clientId)}`:"尚未設定 OAuth Client ID";} function updateFolderStatus(){const folderId=getFolderId(); folderStatus.textContent=folderId?`目前資料夾 ID：${folderId}`:"尚未設定資料夾 ID";}

function getSelectedFiles(){return Array.from(fileInput.files||[]);} function updateSelectedFileInfo(){const files=getSelectedFiles(); if(!files.length){operationInfo.classList.add("hidden"); selectedFileInfo.textContent="尚未選擇檔案"; operationProgressText.textContent=""; operationProgressBar.value=0; return;} operationInfo.classList.remove("hidden"); const total=files.reduce((s,f)=>s+f.size,0); selectedFileInfo.textContent=`已選擇 ${files.length} 個檔案，總大小：${formatFileSize(total)}`; operationProgressText.textContent="等待上傳"; operationProgressBar.value=0;}
function validateUploadFiles(files){const validFiles=[], skippedFiles=[]; for(const file of files){if(file.size>CONFIG.MAX_FILE_SIZE_BYTES)skippedFiles.push({file,reason:"超過單檔 1GB 限制"}); else validFiles.push(file);} return {validFiles,skippedFiles};}
async function uploadSelectedFiles(){if(!ensureReady())return; const files=getSelectedFiles(); if(!files.length)return showMessage("請先選擇一個或多個檔案。","error"); const {validFiles,skippedFiles}=validateUploadFiles(files), successList=[], failedList=[]; if(!validFiles.length){renderUploadSummary(successList,failedList,skippedFiles);return;} uploadBtn.disabled=true; operationInfo.classList.remove("hidden"); operationProgressBar.value=0; for(let i=0;i<validFiles.length;i++){const file=validFiles[i]; updateOperationProgress("上傳",i+1,validFiles.length,file.name); try{const uploaded=await uploadSingleFile(file); successList.push({file,uploaded});}catch(error){failedList.push({file,reason:error.message});} operationProgressBar.value=Math.round(((i+1)/validFiles.length)*100);} uploadBtn.disabled=false; fileInput.value=""; updateSelectedFileInfo(); renderUploadSummary(successList,failedList,skippedFiles); listFiles();}
async function uploadSingleFile(file){const metadata={name:file.name,parents:[getFolderId()]}; const initRes=await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id,name,size,createdTime",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json; charset=UTF-8","X-Upload-Content-Type":file.type||"application/octet-stream","X-Upload-Content-Length":String(file.size)},body:JSON.stringify(metadata)}); if(!initRes.ok)throw new Error(await readGoogleError(initRes)); const uploadUrl=initRes.headers.get("Location"); if(!uploadUrl)throw new Error("無法取得 Google Drive resumable upload URL。"); const uploadRes=await fetch(uploadUrl,{method:"PUT",headers:{"Content-Type":file.type||"application/octet-stream","Content-Length":String(file.size)},body:file}); if(!uploadRes.ok)throw new Error(await readGoogleError(uploadRes)); return uploadRes.json();}
function renderUploadSummary(successList,failedList,skippedList){const parts=[`上傳完成：成功 ${successList.length} 個，失敗 ${failedList.length} 個，略過 ${skippedList.length} 個。`]; if(failedList.length)parts.push("失敗："+failedList.map(x=>`${x.file.name}（${x.reason}）`).join("；")); if(skippedList.length)parts.push("略過："+skippedList.map(x=>`${x.file.name}（${x.reason}）`).join("；")); showMessage(parts.join("\n"),failedList.length?"error":"success");}
function updateOperationProgress(action,current,total,fileName){operationInfo.classList.remove("hidden"); selectedFileInfo.textContent=`${action}作業進行中`; operationProgressText.textContent=`正在${action} ${current} / ${total}：${fileName}`; operationProgressBar.value=Math.round(((current-1)/total)*100);}

function toggleFileSelection(file,checked){if(checked)selectedFiles.set(file.id,{id:file.id,name:file.name}); else selectedFiles.delete(file.id); syncSelectionUI();}
function toggleSelectAllFiles(checked){if(checked) currentFiles.forEach(f=>selectedFiles.set(f.id,{id:f.id,name:f.name})); else selectedFiles.clear(); syncSelectionUI();}
function clearSelectedFiles(){selectedFiles.clear(); syncSelectionUI();}
function syncSelectionUI(){document.querySelectorAll(".file-select-checkbox").forEach(cb=>{cb.checked=selectedFiles.has(cb.dataset.fileId);}); if(selectAllFilesCheckbox)selectAllFilesCheckbox.checked=currentFiles.length>0&&currentFiles.every(f=>selectedFiles.has(f.id)); updateBatchActionBar();}
function updateBatchActionBar(){const count=selectedFiles.size; selectedCountText.textContent=`已選取 ${count} 個檔案`; batchActionBar.classList.toggle("hidden",count===0);}
async function batchDeleteSelectedFiles(){if(!ensureReady())return; const targets=Array.from(selectedFiles.values()); if(!targets.length)return showMessage("請先勾選要刪除的檔案。","error"); const preview=targets.slice(0,10).map(f=>`- ${f.name}`).join("\n"); const more=targets.length>10?`\n以及其他 ${targets.length-10} 個檔案`:""; if(!confirm(`確定要刪除 ${targets.length} 個檔案嗎？此操作無法復原。\n\n將刪除：\n${preview}${more}`))return; batchDeleteBtn.disabled=true; const successList=[], failedList=[]; operationInfo.classList.remove("hidden"); operationProgressBar.value=0; for(let i=0;i<targets.length;i++){const file=targets[i]; updateOperationProgress("刪除",i+1,targets.length,file.name); try{await deleteSingleFile(file); successList.push(file);}catch(error){failedList.push({file,reason:error.message});} operationProgressBar.value=Math.round(((i+1)/targets.length)*100);} batchDeleteBtn.disabled=false; selectedFiles.clear(); renderDeleteSummary(successList,failedList); listFiles();}
async function deleteSingleFile(file){await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}`,{method:"DELETE"});}
function renderDeleteSummary(successList,failedList){const parts=[`批次刪除完成：成功 ${successList.length} 個，失敗 ${failedList.length} 個。`]; if(failedList.length)parts.push("失敗："+failedList.map(x=>`${x.file.name}（${x.reason}）`).join("；")); showMessage(parts.join("\n"),failedList.length?"error":"success");}

async function listFiles(){if(!ensureReady())return; fileTableBody.innerHTML=`<tr><td colspan="7" class="empty">載入中...</td></tr>`; mobileFileList.innerHTML=`<div class="empty">載入中...</div>`; const query=`'${escapeDriveQuery(getFolderId())}' in parents and trashed = false`; const params=new URLSearchParams({q:query,pageSize:"100",orderBy:"createdTime desc",fields:"files(id,name,mimeType,size,createdTime,modifiedTime,owners(displayName,emailAddress),lastModifyingUser(displayName,emailAddress),webContentLink)"}); try{const res=await driveFetch(`https://www.googleapis.com/drive/v3/files?${params.toString()}`); const data=await res.json(); currentFiles=data.files||[]; selectedFiles.clear(); renderFileTable(currentFiles); renderFileCards(currentFiles); syncSelectionUI();}catch(error){showMessage(`讀取檔案失敗：${error.message}`,"error"); fileTableBody.innerHTML=`<tr><td colspan="7" class="empty">讀取失敗</td></tr>`; mobileFileList.innerHTML=`<div class="empty">讀取失敗</div>`;}}
function renderFileTable(files){if(!files.length){fileTableBody.innerHTML=`<tr><td colspan="7" class="empty">此資料夾目前沒有檔案</td></tr>`;return;} fileTableBody.innerHTML=""; files.forEach(file=>{const tr=document.createElement("tr"), uploader=getUploader(file); tr.innerHTML=`<td class="select-col"><input class="file-select-checkbox" data-file-id="${escapeHtml(file.id)}" type="checkbox" aria-label="選取 ${escapeHtml(file.name)}" /></td><td title="${escapeHtml(file.name)}">${escapeHtml(file.name)}</td><td>${formatFileSize(file.size)}</td><td>${escapeHtml(getFileExtension(file.name))}</td><td>${escapeHtml(uploader)}</td><td>${formatDate(file.createdTime)}</td><td><div class="action-group"><button class="btn small" data-action="download">下載</button><button class="btn small" data-action="rename">改名</button><button class="btn small danger" data-action="delete">刪除</button></div></td>`; tr.querySelector(".file-select-checkbox").addEventListener("change",e=>toggleFileSelection(file,e.target.checked)); tr.querySelector('[data-action="download"]').addEventListener("click",()=>downloadFile(file)); tr.querySelector('[data-action="rename"]').addEventListener("click",()=>renameFile(file)); tr.querySelector('[data-action="delete"]').addEventListener("click",()=>deleteFile(file)); fileTableBody.appendChild(tr);});}
function renderFileCards(files){if(!files.length){mobileFileList.innerHTML=`<div class="empty">此資料夾目前沒有檔案</div>`;return;} mobileFileList.innerHTML=""; files.forEach(file=>mobileFileList.appendChild(createFileCard(file)));}
function createFileCard(file){const card=document.createElement("div"); card.className="file-card"; const uploader=getUploader(file); card.innerHTML=`<div class="file-card-head"><input class="file-select-checkbox" data-file-id="${escapeHtml(file.id)}" type="checkbox" aria-label="選取 ${escapeHtml(file.name)}" /><div class="file-card-title">${escapeHtml(file.name)}</div></div><div class="file-meta"><span>大小：${formatFileSize(file.size)}</span><span>副檔名：${escapeHtml(getFileExtension(file.name))}</span><span>上傳者：${escapeHtml(uploader)}</span><span>上傳時間：${formatDate(file.createdTime)}</span></div><div class="file-card-actions"><button class="btn small" data-action="download">下載</button><button class="btn small" data-action="rename">改名</button><button class="btn small danger" data-action="delete">刪除</button></div>`; card.querySelector(".file-select-checkbox").addEventListener("change",e=>toggleFileSelection(file,e.target.checked)); card.querySelector('[data-action="download"]').addEventListener("click",()=>downloadFile(file)); card.querySelector('[data-action="rename"]').addEventListener("click",()=>renameFile(file)); card.querySelector('[data-action="delete"]').addEventListener("click",()=>deleteFile(file)); return card;}
function getUploader(file){return file.owners?.[0]?.displayName||file.owners?.[0]?.emailAddress||file.lastModifyingUser?.displayName||"-";}
async function downloadFile(file){if(!ensureReady())return; try{showMessage(`正在下載：${file.name}`,"info"); const res=await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}?alt=media`); const blob=await res.blob(); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=file.name; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); showMessage("下載完成。","success");}catch(error){showMessage(`下載失敗：${error.message}`,"error");}}
async function renameFile(file){if(!ensureReady())return; const newName=prompt("請輸入新的檔案名稱：",file.name); if(!newName||newName.trim()===file.name)return; try{await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}?fields=id,name`,{method:"PATCH",headers:{"Content-Type":"application/json; charset=UTF-8"},body:JSON.stringify({name:newName.trim()})}); showMessage("檔名已更新。","success"); listFiles();}catch(error){showMessage(`修改檔名失敗：${error.message}`,"error");}}
async function deleteFile(file){if(!ensureReady())return; if(!confirm(`確定要刪除「${file.name}」嗎？此操作無法復原。`))return; try{await deleteSingleFile(file); showMessage("檔案已刪除。","success"); listFiles();}catch(error){showMessage(`刪除失敗：${error.message}`,"error");}}

async function checkForUpdates(){const previousText=checkUpdateBtn.textContent; checkUpdateBtn.disabled=true; checkUpdateBtn.textContent="檢查中..."; updateResult.className="update-result hint"; updateResult.innerHTML="正在檢查 GitHub 版本..."; try{const res=await fetch(buildCacheBustingUrl(getVersionCheckUrl()),{cache:"no-store",headers:{"Cache-Control":"no-cache"}}); if(!res.ok)throw new Error(`${res.status} ${res.statusText}`); const info=await res.json(); validateVersionInfo(info); githubLatestVersion.value=info.latestVersion; const hasUpdate=compareVersions(info.latestVersion,CONFIG.APP_VERSION)>0; updateResult.className=`update-result ${hasUpdate?"update-available":"up-to-date"}`; updateResult.innerHTML=`<div><strong>${hasUpdate?"發現新版本，準備自動更新":"目前已是最新版本"}</strong></div><div>目前：${escapeHtml(CONFIG.APP_VERSION)}</div><div>GitHub：${escapeHtml(info.latestVersion)}</div><div>發布日期：${escapeHtml(info.releaseDate||"-")}</div><div>說明：${escapeHtml(info.releaseNote||"-")}</div>`; if(hasUpdate){await delay(800); await applyPwaUpdate();}}catch(error){updateResult.className="update-result update-error"; updateResult.innerHTML=`檢查更新失敗：${escapeHtml(error.message)}`;}finally{checkUpdateBtn.disabled=false; checkUpdateBtn.textContent=previousText;}}
async function applyPwaUpdate(){if("serviceWorker" in navigator){const regs=await navigator.serviceWorker.getRegistrations(); await Promise.all(regs.map(r=>r.unregister()));} if("caches" in window){const keys=await caches.keys(); await Promise.all(keys.map(k=>caches.delete(k)));} await delay(500); window.location.reload();}
function buildCacheBustingUrl(url){return `${url}${url.includes("?")?"&":"?"}t=${Date.now()}`;} function validateVersionInfo(info){if(!info||typeof info!=="object")throw new Error("version.json 格式錯誤。"); if(!info.latestVersion)throw new Error("version.json 缺少 latestVersion 欄位。");} function normalizeVersion(v){return String(v).trim().replace(/^v/i,"");} function compareVersions(a,b){const pa=normalizeVersion(a).split(".").map(n=>parseInt(n,10)||0), pb=normalizeVersion(b).split(".").map(n=>parseInt(n,10)||0), len=Math.max(pa.length,pb.length); for(let i=0;i<len;i++){if((pa[i]||0)>(pb[i]||0))return 1;if((pa[i]||0)<(pb[i]||0))return -1;}return 0;} function delay(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function driveFetch(url,options={}){if(!accessToken)throw new Error("尚未登入 Google。"); const headers=new Headers(options.headers||{}); headers.set("Authorization",`Bearer ${accessToken}`); const res=await fetch(url,{...options,headers}); if(!res.ok)throw new Error(await readGoogleError(res)); return res;} async function readGoogleError(res){try{const data=await res.json(); return data.error?.message||`${res.status} ${res.statusText}`;}catch{return `${res.status} ${res.statusText}`;}}
function ensureReady(){if(!getGoogleClientId()){showMessage("請先到 Settings 設定 Google OAuth Client ID。","error");switchToSettingsTab();return false;} if(!accessToken){showMessage("請先登入 Google。","error");return false;} if(!getFolderId()){showMessage("請先到 Settings 設定 Google Drive 資料夾 ID。","error");switchToSettingsTab();return false;} return true;}
function initTabs(){document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>switchTab(btn.dataset.tab)));} function switchToSettingsTab(){switchTab("settings");} function switchTab(tabName){document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active")); document.querySelector(`.tab[data-tab="${tabName}"]`)?.classList.add("active"); $("filesTab").classList.remove("active"); $("settingsTab").classList.remove("active"); $(tabName==="files"?"filesTab":"settingsTab").classList.add("active");}
function showMessage(message,type="info"){messageBox.textContent=message; messageBox.className=`message ${type}`; setTimeout(()=>messageBox.classList.add("hidden"),9000);} function isValidClientIdFormat(clientId){return /^\d+-[a-zA-Z0-9_-]+\.apps\.googleusercontent\.com$/.test(clientId);} function maskClientId(clientId){return clientId.length<=20?clientId:`${clientId.slice(0,10)}...${clientId.slice(-24)}`;} function formatFileSize(size){if(!size)return"-"; const units=["B","KB","MB","GB","TB"]; let value=Number(size), index=0; while(value>=1024&&index<units.length-1){value/=1024;index++;} return `${value.toFixed(value>=10?0:1)} ${units[index]}`;} function getFileExtension(name){const index=name.lastIndexOf("."); return index===-1||index===name.length-1?"-":name.substring(index+1).toLowerCase();} function formatDate(dateString){if(!dateString)return"-"; return new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(dateString));} function escapeHtml(str=""){return String(str).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");} function escapeDriveQuery(str=""){return String(str).replaceAll("\\","\\\\").replaceAll("'","\\'");} function registerServiceWorker(){if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));}}
